#!/usr/bin/env bash

export ME=$(readlink -f $0)
. ~/bin/init_sys.sh

# set -vx
export ROOT=~/dev/bdrc-fcrepo-client
export PRODUCT=bdrc-fcrepo-client-1.0-SNAPSHOT
export INSTALL=${PRODUCT}-Install
export LIB=${ROOT}/target/${INSTALL}/${PRODUCT}/lib
export JAR=${ROOT}/target/${PRODUCT}.jar
export VM_ARGS="-Dorg.slf4j.simpleLogger.defaultLogLevel=debug"

ls -l $JAR
ls -l $PRODUCT
ls -l $LIB
read fff  -p "?"
java $VM_ARGS -cp ${JAR}:${LIB} io.bdrc.lib.Main
